# Generated by Django 5.0.6 on 2024-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.SmallIntegerField()),
                ('provider_name', models.CharField(max_length=30)),
                ('billing_details', models.CharField(max_length=60)),
            ],
        ),
    ]
