# Generated by Django 5.0.6 on 2024-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_payment_id', models.SmallIntegerField()),
                ('user_id', models.SmallIntegerField()),
                ('provider_id', models.SmallIntegerField()),
                ('amount', models.SmallIntegerField()),
                ('time_stamp', models.DateField()),
            ],
        ),
    ]
