# Generated by Django 5.0.6 on 2024-07-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rename_user_id_bills_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='user',
            new_name='user_id',
        ),
    ]
