# Generated by Django 5.0.6 on 2024-07-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_user_bills_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='user_id',
            new_name='user',
        ),
    ]
